#!/bin/sh

cd Q-Al-Mg

#module load sphinx/serial/2.0.4
#run this script in main folder Q-Al-Mg

folder=`ls -1d [0-9]*`
here=`pwd`
for f in $folder; do
  echo $f
  cd $f
  volbohr3=`grep --text "optimal volume V0" murn.dat | awk {'print $6'}`
  volang3=` echo "scale=8;21*0.14818471*$volbohr3"|bc `
  mkdir finite
  head -28 1.00/CONTCAR > finite/POSCARraw
  cd finite
  head -1 POSCARraw > POSCAR
  echo '  '-$volang3 >> POSCAR
  head -28 POSCARraw | tail -26 >> POSCAR
  cp ../POTCAR .
  cp ../KPOINTS .
  cp ../Q.sh .
  mkdir relax
  cp ../../../INCARrelax ./relax/INCAR
  mv ./POSCAR ./relax/
  cp ./* ./relax/
  cd $here
done
