#!/bin/sh

cd Q-Al-Mg

#module load sphinx/serial/2.0.4
#run this script in main folder Q-Al-Mg

folder=`ls -1d [0-9]*`
here=`pwd`
for f in $folder; do
  echo $f
  cd $f/finite/relax
  qsub -pe 'mpi*' 24 Q.sh
  cd $here
done

