#!/bin/sh

cd Q-Al-Mg

#module load sphinx/serial/2.0.4
#run this script in main folder Q-Al-Mg

folder=`ls -1d [0-9]*`
here=`pwd`
for f in $folder; do
  echo $f
  cd $f/finite
  head -28 relax/CONTCAR > POSCAR

  echo 'convert POSCAR to strcut'
  sxstructprint --vasp -i POSCAR > struct.sx

  echo 'generating supercell'
  sxstructrep -r 1x1x2 -i struct.sx -o Sstruct.sx > sxstructrep.log

  echo 'convert Supercell to POSCAR'
  sx2poscar -i Sstruct.sx -o SPOSCAR > sx2poscar.log

  echo 'generating displacements'
  sxuniqdispl -d 0.02 -i Sstruct.sx > sxuniqdispl.log

  echo 'generating displaced POSCAR'
  ndir=`ls -1d i*.* | wc -l`
  for (( i=1; i<$ndir+1; i++ )); do 
    sx2poscar -i input-disp-$i.sx -o SPOSCAR$i > sx2poscar.log
    mkdir 1_$i
    mv SPOSCAR$i 1_$i/POSCAR
  done

  echo 'background'
  mkdir forces_background
  mv SPOSCAR forces_background/POSCAR
  
  cd $here
done

