#!/bin/bash

Jname=`ls *.o*`
Job=${1:-$Jname}
#grep DAV $Job | awk '{print $2 "  " $3 "  " $4 "  "  $(NF-1)}' > conv.dat
CAR=`ls OUTCAR*`
zgrep 'free energy    TOTEN' $CAR | awk '{print $(NF-1)}' | cat -n > tmp1
zgrep 'total energy-change' $CAR | awk -F: '{print $2}' | awk '{print $1}'  > tmp2
zgrep 'rms(total)' $CAR | awk '{print $3}' > tmp3
paste tmp1 tmp2 tmp3 > conv.dat
rm tmp1 tmp2 tmp3
#gnuplot -e "filename='conv.dat'" /u/$USER/scripts/conv5skip.plg
#gnuplot -e "filename='conv.dat'; COLUMNS='`echo $COLUMNS`'; LINES='$LINES'" /u/$USER/scripts/conv5skip.plg
L=$LINES
C=$COLUMNS
gnuplot -e "filename='conv.dat'; COL='${C}'; LIN='${L}'" $HOME/scripts/conv5skip.plg


