#!/bin/sh

#module load sphinx/serial/2.0.4

echo 'convert POSCAR to strcut'
sxstructprint --vasp -i POSCAR > struct.sx

echo 'generating supercell'
sxstructrep -r 1x1x2 -i struct.sx -o Sstruct.sx

echo 'convert Supercell to POSCAR'
sx2poscar -i Sstruct.sx -o SPOSCAR

echo 'generating displacements'
sxuniqdispl -d 0.02 -i Sstruct.sx

echo 'generating displaced POSCAR'
nodir=`ls -1d i*.* | wc -l`
for (( i=1; i<$nodir+1; i++ )); do 
sx2poscar -i input-disp-$i.sx -o SPOSCAR$i
mkdir 1_$i
cp SPOSCAR$i 1_$i/POSCAR
done

echo 'making directories and copying files'
mkdir forces_background
cp SPOSCAR forces_background/POSCAR


