#!/bin/sh

folder=`ls -1d [0-9]*`
hier=`pwd`

for f in $folder; do
echo $f
cd $f

lat=(0.96 0.97 0.98 0.99 1.00 1.01 1.02 1.03 1.04)
for a in "${lat[@]}"; do


  mkdir $a
  cd $a
  
  cp ../../script.parallel.sh ./
  cp ../../INCAR ./
  cp ../../KPOINTS ./
  cp ../POTCAR ./
  cp ../POSCAR ./

#--- prompt user info
  echo "-------------------------------------------------------"
  echo "  Lat. coef. = $a"
  echo "-------------------------------------------------------"

#--- create POSCAR
  mv POSCAR POSCARtmp
  head -1 POSCARtmp >> POSCAR

  cat >> POSCAR << POSCAReof
$a
POSCAReof
  tail -27 POSCARtmp >> POSCAR
  qsub -pe 'mpi*' 24 script.parallel.sh
  cd ../
done
cd $hier
done

